### ISSUE TITLE
你好，我在使用VGG 模型中遇到了问题

### ISSUE THREAD

**Issue by HFourier** [qyy2003/FTPipeHD#1]
当我使用vgg_config.yml进行训练时，运行main.py文件报错如下：
`Traceback (most recent call last):
  File "/home/nahida/workspace/FTPipeHD/main.py", line 65, in <module>
    main()
  File "/home/nahida/workspace/FTPipeHD/main.py", line 40, in main
    single_train(args)
  File "/home/nahida/workspace/FTPipeHD/main.py", line 47, in single_train
    train_single()
  File "/home/nahida/workspace/FTPipeHD/utils/train_single.py", line 45, in train_single
    train_epoch(model, optimizer, lr, train_dataloader, test_dataloader, epoch)
  File "/home/nahida/workspace/FTPipeHD/utils/train_single.py", line 62, in train_epoch
    cur_loss, cur_correct,num = train_step(batch, model, optimizer, iter_id)
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/anaconda3/lib/python3.11/site-packages/memory_profiler.py", line 1188, in wrapper
    val = prof(func)(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/anaconda3/lib/python3.11/site-packages/memory_profiler.py", line 761, in f
    return func(*args, **kwds)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/nahida/workspace/FTPipeHD/utils/train_single.py", line 99, in train_step
    outputs,loss = model(**batch)
argument` after ** must be a mapping, not list`
我猜测是这里的batch是应对处理如BERT等预训练模型时，输入会以键值对的形式组织，但VGG 的输入是list形式，请问作者这里我需要在哪里进行修改吗？

**Comment by qyy2003** [comment]
Yes, just as you have stated, we organized the data in ```dict``` to handle the multiple inputs of the language model, and thus not compatible with the original image model.  We do not maintain the image model anymore. Sorry about that.
